name: CI

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  REPOSITORY: kubeflow-notebook

jobs:
  build:
    strategy:
      matrix:
        base_image:
          - ghcr.io/kubeflow-notebook/jupyter-pytorch-cuda-full
          - ghcr.io/kubeflow-notebook/jupyter-tensorflow-cuda-full
        kubeflow_version:
          - v1.8.0
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.base_image }}-cn
          tags: |
            ${{ matrix.kubeflow_version }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_IMAGE=${{ matrix.base_image }}
            KUBEFLOW_VERSION=${{ matrix.kubeflow_version }}
